version: "3.8"
services:
  web:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - backbone
  api:
    build: ./backend
    networks:
      - backbone
    ports:
      - 4000:4000
  nginx:
    build: ./nginx
    networks:
      - backbone
    ports:
      - 80:80

networks:
  backbone:
    driver: bridge
